version: '3.6'
# Coba cek ga pakai links masih bisa atau engga

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  backend:
    container_name: web
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    volumes:
      - './app/:/usr/local/application'
      - '/usr/local/application/backend/node_modules'
  frontend:
    container_name: client
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - '3002:3000'
    volumes:
      - './app/frontend:/var/www/html'
      - '/var/www/html/node_modules'